# Use the official MongoDB image as the base image
FROM mongo:latest

# Optionally copy initialization scripts (e.g., for creating users, collections)
# COPY ./init-db.js /docker-entrypoint-initdb.d/

# Expose MongoDB port (default 27017)
EXPOSE 27017
